variables:
  BOT_COMMAND_PREFIX: "."


  ADMIN_ID: 1234


  ADMINS_LIST:




cogs:
  cogs_manager: null # No needed any data

  # Systems:
  clear_chat: ADMINS_LIST
  json: null # No needed any data

  # Events:
  on_member_join: null
  on_ready: null

  # Achievements:
  achievements: null
  refresh: null

