database:
  PATH_DATABASE: 'bot/database/database.sqlite'





variables:
  BOT_COMMAND_PREFIX: "."
  ADMIN_ID: 1234
  ADMINS_LIST: [123, 1234]


#cogs:
#  cogs_manager:
#      cogs_manager: null
#
#  systems:
#    clear_chat: null
#    json: null
#
#  events:
#    on_member_join: null
#    on_ready: null
#
#  achievements:
#    achievements: null
#    refresh: null
