database:
  PATH_DATABASE: 'bot/database/database.sqlite'

roles_ids:
  other:

variables:
  BOT_COMMAND_PREFIX: "/"
  ADMIN_ID:
  ADMINS_LIST:

events:
  on_member_join:
    id_text_channel_for_welcome:
    captchas_saving_path: "bot/cogs/events/captchas"
    captcha_prefix: 'WeFi'

tasks:
  activity:
    id_role_for_activity_track:
    id_text_channel_for_report:

