database:
  PATH_DATABASE: 'bot/database/database.sqlite'






variables:
  BOT_COMMAND_PREFIX: "."
  ADMIN_ID:
  ADMINS_LIST:


tasks:
  activity:
    id_role_for_activity_track: 952280483759292456
    id_text_channel_for_report: 952607509649190962

#cogs:
#  cogs_manager:
#      cogs_manager: null
#
#  systems:
#    clear_chat: null
#    json: null
#
#  events:
#    on_member_join: null
#    on_ready: null
#
#  achievements:
#    achievements: null
#    refresh: null
