database:
  PATH_DATABASE: "bot/database/database.sqlite"

roles_ids:
  other: 952282700780281938

variables:
  BOT_COMMAND_PREFIX: "/"
  ADMIN_ID:
  ADMINS_LIST:

events:
  on_member_join:
    id_text_channel_for_welcome: 952278528458641438
    captchas_saving_path: "bot/cogs/events/captchas"
    captcha_prefix: "WeFi"

tasks:
  activity:
    id_role_for_activity_track: 952280483759292456
    id_text_channel_for_report: 954793683323064401

cogs:
  activity:
    message_expiration_time: 5

# Format like: "Europe/Kyiv"
timezone: "Europe/Kyiv"

